### ISSUE TITLE
RajawaliVRExample Crash when resuming from Screen Off

### ISSUE THREAD

**Issue by OnlyInAmerica** [Rajawali/RajawaliVR#1]
The RajawaliVRExample application provokes a crash within the Rajawali library when being resumed after a screen off pause. Here's the stack trace I experience on my Nexus5 on the L Developer Preview.

```
am_on_paused_called  I  [0,rajawali.vr.example.RajawaliVRExampleActivity]
        AndroidRuntime  E  FATAL EXCEPTION: GLThread 3212
                        E  Process: rajawali.vr.example, PID: 353
                        E  java.lang.IllegalArgumentException: bitmap is recycled
                        E      at android.opengl.GLUtils.texImage2D(GLUtils.java:112)
                        E      at rajawali.materials.textures.ASingleTexture.add(ASingleTexture.java:187)
                        E      at rajawali.materials.textures.TextureManager.taskAdd(TextureManager.java:116)
                        E      at rajawali.materials.textures.TextureManager.taskAdd(TextureManager.java:87)
                        E      at rajawali.renderer.RajawaliRenderer.internalAddTexture(RajawaliRenderer.java:935)
                        E      at rajawali.renderer.RajawaliRenderer.handleAddTask(RajawaliRenderer.java:736)
                        E      at rajawali.renderer.RajawaliRenderer.performFrameTasks(RajawaliRenderer.java:676)
                        E      at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:352)
                        E      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
                        E      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

I've worked through the difficulties of this particular transition on another project, so I'm familiar with the trickery of the OpenGL Context being destroyed after screen off even when it's requested to be preserved. Perhaps that's the root issue here?

Love your work!

**Comment by MasDennis** [comment]
This should be fixed. Closing this issue.
